# Generated by Django 5.0.6 on 2024-05-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Customer',
            new_name='customer',
        ),
    ]
