# Generated by Django 5.0.6 on 2024-05-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_customer_orders_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
