# Generated by Django 5.0.6 on 2024-05-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_orders_address_orders_mobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
